spring:
  application:
    name: libraryapi
  output:
    ansi:
      enabled:
        ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5434/library
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #none, create-drop
    properties:
      hibernate.format_sql: true
logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: trace #trace, debug, info, warn, error
    io:
      github:
        psm0015:
          controller: trace
    org:
      springframework:
        web: trace
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
#        include: '*'
        include: beans, logfile